title: Honors Physical Computing
description: The Honors Physical Computing course at Lane Tech HS
theme: just-the-docs

url: https://chinesefellow.github.io/pclcourse

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
